server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index proposal.pdf;

        # Open the PDF inline in the browser instead of forcing a download
        location ~* \.pdf$ {
            add_header Content-Type application/pdf;
            add_header Content-Disposition inline;
        }
    }
}
